export const CartActionTypes ={
    TOGGLE_CART_HIDDENT : 'TOGGLE_CART_HIDDENT',
    ADD_ITEM:'ADD_ITEM',
    DECREASE_IETEM_QUANTITY:'DECREASE_IETEM_QUANTITY',
    REMOVE_ITEM_FROM_CART:'REMOVE_ITEM_FROM_CART',
}